#!/usr/bin/env node
import { existsSync, readFileSync, readdirSync, mkdirSync, writeFileSync, statSync } from 'node:fs';
import { join, extname, basename } from 'node:path';

const THRESHOLDS = {
  GOD_CLASS_LINES: 500,
  LONG_METHOD_LINES: 100,
  HIGH_METHOD_COUNT: 15,
  MAGIC_NUMBER_MIN_CLUSTER: 5,
  DEEP_NESTING_LEVELS: 5,
  DEEP_NESTING_CONSECUTIVE: 10,
  MAX_FILE_SIZE: 512 * 1024,
  MAX_CANDIDATES: 50,
  MAX_EVIDENCE_PER_CANDIDATE: 5,
};

const SOURCE_EXTENSIONS = new Set([
  '.java', '.kt', '.scala', '.groovy',
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
  '.py', '.pyw',
  '.go', '.rs', '.rb', '.php', '.cs', '.swift', '.dart',
  '.c', '.h', '.cpp', '.hpp', '.cc', '.cxx',
  '.lua', '.vue', '.svelte',
]);

const BRACE_LANGUAGES = new Set([
  '.java', '.kt', '.scala', '.groovy',
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
  '.go', '.rs', '.cs', '.swift', '.dart',
  '.c', '.h', '.cpp', '.hpp', '.cc', '.cxx',
  '.php', '.vue', '.svelte',
]);

const SUPPRESSION_PATTERNS = [
  { regex: /eslint-disable/, label: 'eslint-disable' },
  { regex: /@SuppressWarnings/, label: '@SuppressWarnings' },
  { regex: /noinspection\s/, label: 'noinspection' },
  { regex: /NOSONAR/, label: 'NOSONAR' },
  { regex: /type:\s*ignore/, label: 'type: ignore' },
  { regex: /pragma:\s*no\s*cover/, label: 'pragma: no cover' },
  { regex: /@ts-ignore/, label: '@ts-ignore' },
  { regex: /@ts-expect-error/, label: '@ts-expect-error' },
  { regex: /#\s*nosec/, label: '#nosec' },
];

const GENERATED_MARKERS = [
  /DO NOT EDIT/i,
  /AUTO[- ]?GENERATED/i,
  /@generated\b/,
  /Generated by\b/i,
  /Code generated by\b/i,
  /THIS FILE IS GENERATED/i,
];

const CONTRACT_EXTENSIONS = new Set(['.proto', '.thrift', '.avsc', '.wsdl', '.xsd']);
const CONTRACT_NAME_PATTERNS = [
  /swagger.*\.(json|ya?ml)$/i,
  /openapi.*\.(json|ya?ml)$/i,
  /.*\.graphql$/i,
  /.*\.gql$/i,
];

const METHOD_PATTERNS = {
  brace: [
    /(?:function\s+\w+|(?:async\s+)?(?:get|set|static|public|private|protected|override)?\s*\w+\s*\([^)]*\)\s*(?::\s*\w+)?\s*\{)/,
    /(?:(?:public|private|protected|internal|static|abstract|override|virtual|async|final|synchronized)\s+)*\w[\w<>,\s]*\s+\w+\s*\([^)]*\)\s*(?:throws\s+[\w,\s]+)?\s*\{/,
    /=>\s*\{/,
  ],
  python: /^(\s*)def\s+\w+/,
};

const MAGIC_NUMBER_REGEX = /(?<![.\w])(-?\d+\.?\d*)\b/g;
const MAGIC_NUMBER_WHITELIST = new Set([
  '0', '1', '2', '3', '4', '5', '-1', '-2', '0.0', '1.0',
  '100', '1000', '1024',
  '200', '201', '204', '301', '302', '304', '400', '401', '403', '404', '405', '409', '422', '429', '500', '502', '503', '504',
  '80', '443', '8080', '8443', '3000', '3001', '5000', '5432', '3306', '6379', '27017',
  '10', '60', '24', '365', '360', '180', '90',
  '255', '256', '512', '1048576',
]);

const DEBT_TODO_REGEX = /(?:TODO|FIXME|HACK|XXX)\s*[:\-]?\s*(.{10,})/i;
const DEBT_SIGNAL_WORDS = /workaround|temporary|temp\b|legacy|backward.?compat|兼容|临时|变通|hack|kludge|quick.?fix|技术债/i;

const COMPLEXITY_KEYWORDS = /\b(?:if|else\s+if|elif|switch|case|for|while|catch|except)\b|\?\s*[^:]+\s*:/g;

const CATEGORY_PREFIX = { forbidden_zone: 'fz', weird_but_intentional: 'wbi', smell: 'dnr' };

// --- Source file filtering ---

function getSourceFiles(projectRoot, repoMap) {
  const sourceDirs = new Set();
  for (const dir of repoMap.directory_summary || []) {
    if (dir.role === 'source') sourceDirs.add(dir.path);
  }

  const allFiles = [];
  try {
    const files = JSON.parse(JSON.stringify(repoMap))._all_files;
    if (Array.isArray(files)) return files.filter(f => isSourceFile(f, sourceDirs));
  } catch { /* fallback */ }

  const listDir = (dir, rel) => {
    let entries;
    try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      const relPath = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        if (['node_modules', '.git', 'dist', 'build', 'target', '__pycache__', '.next', '.nuxt', 'vendor', 'venv', '.venv', 'coverage'].includes(entry.name)) continue;
        listDir(fullPath, relPath);
      } else if (entry.isFile() && isSourceFile(relPath, sourceDirs)) {
        allFiles.push(relPath);
      }
    }
  };
  listDir(projectRoot, '');
  return allFiles;
}

function isSourceFile(filePath, sourceDirs) {
  const ext = extname(filePath);
  if (!SOURCE_EXTENSIONS.has(ext)) return false;
  if (sourceDirs.size === 0) return true;
  for (const dir of sourceDirs) {
    if (filePath.startsWith(dir + '/') || filePath.startsWith(dir)) return true;
  }
  return true;
}

function safeReadFile(fullPath) {
  try {
    const stat = statSync(fullPath);
    if (stat.size > THRESHOLDS.MAX_FILE_SIZE) return null;
    return readFileSync(fullPath, 'utf8');
  } catch { return null; }
}

// --- Detectors ---

function detectGodClass(ctx) {
  const nonBlank = ctx.lines.filter(l => l.trim()).length;
  if (nonBlank < THRESHOLDS.GOD_CLASS_LINES) return [];
  return [{
    detectorId: 'god-class',
    category: 'smell',
    file: ctx.file,
    lineStart: 1,
    lineEnd: ctx.lines.length,
    note: `${nonBlank} 行非空代码`,
    keywords: ['god-class'],
    qualityScore: Math.min(0.95, 0.7 + (nonBlank - THRESHOLDS.GOD_CLASS_LINES) / 5000),
    content: {
      '坏味道': `上帝类：文件有 ${nonBlank} 行非空代码`,
      '位置': ctx.file,
      '本次不处理原因': '自动检测，待人工确认',
    },
  }];
}

function detectLongMethod(ctx) {
  const ext = extname(ctx.file);
  if (ext === '.py' || ext === '.pyw') return detectLongMethodPython(ctx);
  if (!BRACE_LANGUAGES.has(ext)) return [];
  return detectLongMethodBrace(ctx);
}

function detectLongMethodBrace(ctx) {
  const findings = [];
  const lines = ctx.lines;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const isMethodStart = METHOD_PATTERNS.brace.some(p => p.test(line));
    if (!isMethodStart) continue;

    let depth = 0;
    let started = false;
    let methodEnd = i;
    for (let j = i; j < lines.length; j++) {
      for (const ch of lines[j]) {
        if (ch === '{') { depth++; started = true; }
        if (ch === '}') depth--;
      }
      if (started && depth <= 0) { methodEnd = j; break; }
      if (j === lines.length - 1) methodEnd = j;
    }

    const bodyLines = methodEnd - i + 1;
    if (bodyLines >= THRESHOLDS.LONG_METHOD_LINES) {
      const methodName = extractMethodName(line);
      findings.push({
        detectorId: 'long-method',
        category: 'smell',
        file: ctx.file,
        lineStart: i + 1,
        lineEnd: methodEnd + 1,
        note: `方法 ${methodName} 有 ${bodyLines} 行`,
        keywords: ['long-method'],
        qualityScore: Math.min(0.9, 0.7 + (bodyLines - THRESHOLDS.LONG_METHOD_LINES) / 1000),
        content: {
          '坏味道': `长方法：${methodName} 有 ${bodyLines} 行代码`,
          '位置': `${ctx.file}:${i + 1}`,
          '本次不处理原因': '自动检测，待人工确认',
        },
      });
    }
  }
  return findings;
}

function detectLongMethodPython(ctx) {
  const findings = [];
  const lines = ctx.lines;
  for (let i = 0; i < lines.length; i++) {
    const match = lines[i].match(METHOD_PATTERNS.python);
    if (!match) continue;
    const baseIndent = match[1].length;
    let methodEnd = i;
    for (let j = i + 1; j < lines.length; j++) {
      const trimmed = lines[j].trim();
      if (!trimmed) continue;
      const indent = lines[j].length - lines[j].trimStart().length;
      if (indent <= baseIndent) break;
      methodEnd = j;
    }
    const bodyLines = methodEnd - i + 1;
    if (bodyLines >= THRESHOLDS.LONG_METHOD_LINES) {
      const methodName = lines[i].trim().replace(/^def\s+(\w+).*/, '$1');
      findings.push({
        detectorId: 'long-method',
        category: 'smell',
        file: ctx.file,
        lineStart: i + 1,
        lineEnd: methodEnd + 1,
        note: `方法 ${methodName} 有 ${bodyLines} 行`,
        keywords: ['long-method'],
        qualityScore: Math.min(0.9, 0.7 + (bodyLines - THRESHOLDS.LONG_METHOD_LINES) / 1000),
        content: {
          '坏味道': `长方法：${methodName} 有 ${bodyLines} 行代码`,
          '位置': `${ctx.file}:${i + 1}`,
          '本次不处理原因': '自动检测，待人工确认',
        },
      });
    }
  }
  return findings;
}

function extractMethodName(line) {
  const match = line.match(/(?:function\s+(\w+)|(\w+)\s*\(|(\w+)\s*=\s*(?:async\s+)?(?:function|\())/);
  return match ? (match[1] || match[2] || match[3] || 'anonymous') : 'anonymous';
}

function detectSuppressionComments(ctx) {
  const hits = [];
  for (let i = 0; i < ctx.lines.length; i++) {
    const line = ctx.lines[i];
    for (const { regex, label } of SUPPRESSION_PATTERNS) {
      if (regex.test(line)) {
        hits.push({ lineNum: i + 1, label, snippet: line.trim().slice(0, 120) });
        break;
      }
    }
  }
  if (hits.length === 0) return [];

  const labels = [...new Set(hits.map(h => h.label))];
  const evidence = hits.slice(0, THRESHOLDS.MAX_EVIDENCE_PER_CANDIDATE).map(h => ({
    file: ctx.file,
    line_start: h.lineNum,
    line_end: h.lineNum,
    note: `${h.label}: ${h.snippet}`,
  }));

  return [{
    detectorId: 'suppression-comments',
    category: 'weird_but_intentional',
    file: ctx.file,
    lineStart: hits[0].lineNum,
    lineEnd: hits[hits.length - 1].lineNum,
    note: `${hits.length} 处 lint 抑制注释 (${labels.join(', ')})`,
    keywords: ['suppression-comment', ...labels],
    qualityScore: Math.min(0.9, 0.6 + hits.length * 0.05),
    content: {
      '现象': `该文件包含 ${hits.length} 处 lint/类型检查抑制注释 (${labels.join(', ')})`,
      '原因': '自动检测，具体意图需人工确认',
    },
    _evidence: evidence,
  }];
}

function detectGeneratedCode(ctx) {
  const headerLines = ctx.lines.slice(0, 30);
  for (let i = 0; i < headerLines.length; i++) {
    for (const marker of GENERATED_MARKERS) {
      if (marker.test(headerLines[i])) {
        return [{
          detectorId: 'generated-code',
          category: 'forbidden_zone',
          file: ctx.file,
          lineStart: i + 1,
          lineEnd: i + 1,
          note: `生成代码标记: ${headerLines[i].trim().slice(0, 100)}`,
          keywords: ['generated-code'],
          qualityScore: 0.95,
          content: {
            '范围': ctx.file,
            '原因': '文件包含代码生成标记，不应手动修改',
          },
        }];
      }
    }
  }
  return [];
}

function detectExternalContracts(ctx) {
  const ext = extname(ctx.file);
  const name = basename(ctx.file);

  const isContract = CONTRACT_EXTENSIONS.has(ext) || CONTRACT_NAME_PATTERNS.some(p => p.test(name));
  if (!isContract) return [];

  return [{
    detectorId: 'external-contracts',
    category: 'forbidden_zone',
    file: ctx.file,
    lineStart: 1,
    lineEnd: Math.min(ctx.lines.length, 10),
    note: `外部契约文件: ${name}`,
    keywords: ['external-contract', ext.replace('.', '')],
    qualityScore: 0.9,
    content: {
      '范围': ctx.file,
      '原因': '外部契约文件，修改需确认上下游兼容',
    },
  }];
}

function detectMagicNumbers(ctx) {
  const ext = extname(ctx.file);
  if (!BRACE_LANGUAGES.has(ext) && ext !== '.py' && ext !== '.pyw') return [];

  const magicHits = [];
  for (let i = 0; i < ctx.lines.length; i++) {
    const line = ctx.lines[i];
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('//') || trimmed.startsWith('#') || trimmed.startsWith('*') || trimmed.startsWith('/*')) continue;
    if (/^\s*(?:const|final|static|#define)\b/.test(line)) continue;
    if (/^[A-Z_]+\s*[=:]/.test(trimmed)) continue;
    if (/^\w+:\s*[-\d]/.test(trimmed)) continue;
    if (/import\s|require\(|from\s/.test(trimmed)) continue;
    if (/new\s+Set\s*\(|new\s+Map\s*\(/.test(trimmed)) continue;

    let match;
    const regex = new RegExp(MAGIC_NUMBER_REGEX.source, MAGIC_NUMBER_REGEX.flags);
    while ((match = regex.exec(trimmed)) !== null) {
      const num = match[1];
      if (MAGIC_NUMBER_WHITELIST.has(num)) continue;
      if (/^\d+\.\d+\.\d+/.test(num)) continue;
      if (/^0\.\d+$/.test(num)) continue;
      magicHits.push({ lineNum: i + 1, value: num });
    }
  }

  if (magicHits.length < THRESHOLDS.MAGIC_NUMBER_MIN_CLUSTER) return [];

  const evidence = magicHits.slice(0, THRESHOLDS.MAX_EVIDENCE_PER_CANDIDATE).map(h => ({
    file: ctx.file,
    line_start: h.lineNum,
    line_end: h.lineNum,
    note: `魔法数字: ${h.value}`,
  }));

  return [{
    detectorId: 'magic-numbers',
    category: 'smell',
    file: ctx.file,
    lineStart: magicHits[0].lineNum,
    lineEnd: magicHits[magicHits.length - 1].lineNum,
    note: `${magicHits.length} 个魔法数字`,
    keywords: ['magic-number'],
    qualityScore: Math.min(0.8, 0.5 + magicHits.length * 0.03),
    content: {
      '坏味道': `该文件包含 ${magicHits.length} 个未命名的魔法数字`,
      '位置': ctx.file,
      '本次不处理原因': '自动检测，待人工确认',
    },
    _evidence: evidence,
  }];
}

function detectTodoDebt(ctx) {
  const hits = [];
  for (let i = 0; i < ctx.lines.length; i++) {
    const match = ctx.lines[i].match(DEBT_TODO_REGEX);
    if (!match) continue;
    const text = match[1];
    if (!DEBT_SIGNAL_WORDS.test(text)) continue;
    hits.push({ lineNum: i + 1, text: text.trim().slice(0, 100) });
  }
  if (hits.length === 0) return [];

  const evidence = hits.slice(0, THRESHOLDS.MAX_EVIDENCE_PER_CANDIDATE).map(h => ({
    file: ctx.file,
    line_start: h.lineNum,
    line_end: h.lineNum,
    note: h.text,
  }));

  return [{
    detectorId: 'todo-debt',
    category: 'weird_but_intentional',
    file: ctx.file,
    lineStart: hits[0].lineNum,
    lineEnd: hits[hits.length - 1].lineNum,
    note: `${hits.length} 处含技术债信号的 TODO/FIXME/HACK`,
    keywords: ['todo-debt', 'technical-debt'],
    qualityScore: Math.min(0.85, 0.6 + hits.length * 0.05),
    content: {
      '现象': `该文件包含 ${hits.length} 处含技术债信号的注释`,
      '原因': '自动检测，注释表明存在已知的变通方案或历史包袱',
    },
    _evidence: evidence,
  }];
}

function detectDeepNesting(ctx) {
  const ext = extname(ctx.file);
  if (ext === '.py' || ext === '.pyw') return [];
  if (!BRACE_LANGUAGES.has(ext)) return [];

  let consecutive = 0;
  let nestStart = -1;
  const regions = [];

  for (let i = 0; i < ctx.lines.length; i++) {
    const line = ctx.lines[i];
    const trimmed = line.trim();
    if (!trimmed) continue;
    const leadingSpaces = line.length - line.trimStart().length;
    const tabAdjusted = line.match(/^\t*/)?.[0].length * 4 + (leadingSpaces - (line.match(/^\t*/)?.[0].length * 1 || 0));
    const depth = Math.floor(tabAdjusted / 4);

    if (depth >= THRESHOLDS.DEEP_NESTING_LEVELS) {
      if (consecutive === 0) nestStart = i;
      consecutive++;
    } else {
      if (consecutive >= THRESHOLDS.DEEP_NESTING_CONSECUTIVE) {
        regions.push({ start: nestStart + 1, end: nestStart + consecutive, lines: consecutive });
      }
      consecutive = 0;
    }
  }
  if (consecutive >= THRESHOLDS.DEEP_NESTING_CONSECUTIVE) {
    regions.push({ start: nestStart + 1, end: nestStart + consecutive, lines: consecutive });
  }

  if (regions.length === 0) return [];

  const evidence = regions.slice(0, THRESHOLDS.MAX_EVIDENCE_PER_CANDIDATE).map(r => ({
    file: ctx.file,
    line_start: r.start,
    line_end: r.end,
    note: `${r.lines} 行连续深嵌套（≥${THRESHOLDS.DEEP_NESTING_LEVELS} 层）`,
  }));

  return [{
    detectorId: 'deep-nesting',
    category: 'smell',
    file: ctx.file,
    lineStart: regions[0].start,
    lineEnd: regions[regions.length - 1].end,
    note: `${regions.length} 处深嵌套区域`,
    keywords: ['deep-nesting', 'callback-hell'],
    qualityScore: Math.min(0.85, 0.6 + regions.length * 0.1),
    content: {
      '坏味道': `该文件包含 ${regions.length} 处连续深嵌套区域（≥${THRESHOLDS.DEEP_NESTING_LEVELS} 层嵌套）`,
      '位置': ctx.file,
      '本次不处理原因': '自动检测，待人工确认',
    },
    _evidence: evidence,
  }];
}

// --- Follow-up detectors ---

function followUpHighMethodCount(ctx, seedFinding) {
  const ext = extname(ctx.file);
  let count = 0;
  if (ext === '.py' || ext === '.pyw') {
    for (const line of ctx.lines) {
      if (METHOD_PATTERNS.python.test(line)) count++;
    }
  } else if (BRACE_LANGUAGES.has(ext)) {
    for (const line of ctx.lines) {
      if (METHOD_PATTERNS.brace.some(p => p.test(line))) count++;
    }
  }
  if (count >= THRESHOLDS.HIGH_METHOD_COUNT) {
    seedFinding.note += `，包含 ${count} 个方法`;
    seedFinding.keywords.push('high-method-count');
    seedFinding.content['坏味道'] += `，包含 ${count} 个方法`;
    seedFinding.qualityScore = Math.min(0.95, seedFinding.qualityScore + 0.05);
  }
  return [];
}

function followUpComplexityIndicators(ctx, seedFinding) {
  const startLine = (seedFinding.lineStart || 1) - 1;
  const endLine = (seedFinding.lineEnd || ctx.lines.length) - 1;
  let count = 0;
  for (let i = startLine; i <= endLine && i < ctx.lines.length; i++) {
    const matches = ctx.lines[i].match(COMPLEXITY_KEYWORDS);
    if (matches) count += matches.length;
  }
  if (count > 10) {
    seedFinding.note += `，复杂度指标 ${count}`;
    seedFinding.keywords.push('high-complexity');
  }
  return [];
}

const FOLLOW_UP_MAP = {
  'god-class': [followUpHighMethodCount, followUpComplexityIndicators],
  'long-method': [followUpComplexityIndicators],
};

// --- Main scan function ---

const FILE_DETECTORS = [
  { id: 'god-class', detect: detectGodClass },
  { id: 'long-method', detect: detectLongMethod },
  { id: 'suppression-comments', detect: detectSuppressionComments },
  { id: 'generated-code', detect: detectGeneratedCode },
  { id: 'external-contracts', detect: detectExternalContracts },
  { id: 'magic-numbers', detect: detectMagicNumbers },
  { id: 'todo-debt', detect: detectTodoDebt },
  { id: 'deep-nesting', detect: detectDeepNesting },
];

export function runDebtScan(projectRoot, repoMap, options = {}) {
  let sourceFiles = getSourceFiles(projectRoot, repoMap);
  if (options.scopeDirs && options.scopeDirs.length > 0) {
    sourceFiles = sourceFiles.filter(f => options.scopeDirs.some(d => f.startsWith(d)));
  }
  const allFindings = [];

  for (const file of sourceFiles) {
    const content = safeReadFile(join(projectRoot, file));
    if (!content) continue;
    const lines = content.split('\n');
    const ctx = { file, content, lines, projectRoot, repoMap };

    const fileFindings = [];
    for (const detector of FILE_DETECTORS) {
      fileFindings.push(...detector.detect(ctx));
    }

    for (const finding of fileFindings) {
      const followUps = FOLLOW_UP_MAP[finding.detectorId];
      if (followUps) {
        for (const fn of followUps) fn(ctx, finding);
      }
    }

    allFindings.push(...fileFindings);
  }

  return deduplicateAndCap(allFindings);
}

function deduplicateAndCap(findings) {
  const grouped = new Map();
  for (const f of findings) {
    const key = `${f.file}::${f.category}::${f.detectorId}`;
    if (!grouped.has(key)) {
      grouped.set(key, f);
    } else {
      const existing = grouped.get(key);
      if (f._evidence) {
        existing._evidence = existing._evidence || [];
        existing._evidence.push(...f._evidence);
      }
      if (f.qualityScore > existing.qualityScore) existing.qualityScore = f.qualityScore;
    }
  }

  const deduped = [...grouped.values()];
  deduped.sort((a, b) => b.qualityScore - a.qualityScore);
  return deduped.slice(0, THRESHOLDS.MAX_CANDIDATES);
}

function findingsToJson(findings) {
  const counters = { fz: 0, wbi: 0, dnr: 0 };
  const now = new Date().toISOString();

  return findings.map(f => {
    const prefix = CATEGORY_PREFIX[f.category] || 'dnr';
    counters[prefix] = (counters[prefix] || 0) + 1;
    const id = `${prefix}-scan-${String(counters[prefix]).padStart(3, '0')}`;

    const evidence = f._evidence || [{
      file: f.file,
      line_start: f.lineStart,
      line_end: f.lineEnd,
      note: f.note,
    }];

    return {
      id,
      category: f.category,
      status: 'proposed',
      confirmed: false,
      source_step: 'debt-scan',
      created_at: now,
      quality_score: Math.round(f.qualityScore * 100) / 100,
      keywords: [...new Set(f.keywords)],
      evidence: evidence.slice(0, THRESHOLDS.MAX_EVIDENCE_PER_CANDIDATE),
      content: f.content,
      decision: null,
      merge: null,
    };
  });
}

function writeFindings(outputDir, findings) {
  if (!existsSync(outputDir)) mkdirSync(outputDir, { recursive: true });

  const existing = new Set();
  try {
    for (const f of readdirSync(outputDir)) {
      if (f.endsWith('.json') && f.includes('-scan-')) existing.add(f.replace('.json', ''));
    }
  } catch { /* empty dir */ }

  const candidates = findingsToJson(findings);
  let written = 0;
  for (const candidate of candidates) {
    if (existing.has(candidate.id)) continue;
    const filePath = join(outputDir, `${candidate.id}.json`);
    writeFileSync(filePath, JSON.stringify(candidate, null, 2) + '\n');
    written++;
  }
  return { total: candidates.length, written, skipped: candidates.length - written };
}

// --- CLI ---

function printUsage() {
  process.stderr.write('用法: node debt-scan.mjs --project-root <path> --repo-map <repo-map.json> --output <dir>\n');
}

function parseArgs(args) {
  const result = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--project-root' && args[i + 1]) result.projectRoot = args[++i];
    else if (args[i] === '--repo-map' && args[i + 1]) result.repoMap = args[++i];
    else if (args[i] === '--output' && args[i + 1]) result.output = args[++i];
    else if (args[i] === '--scope-dirs' && args[i + 1]) result.scopeDirs = args[++i];
  }
  return result;
}

const isMain = process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/'));

if (isMain) {
  const args = parseArgs(process.argv.slice(2));
  if (!args.projectRoot || !args.repoMap || !args.output) {
    printUsage();
    process.exit(1);
  }

  if (!existsSync(args.repoMap)) {
    process.stderr.write(`错误: repo-map 文件不存在: ${args.repoMap}\n`);
    process.exit(1);
  }

  let repoMap;
  try {
    repoMap = JSON.parse(readFileSync(args.repoMap, 'utf8'));
  } catch (e) {
    process.stderr.write(`错误: repo-map JSON 解析失败: ${e.message}\n`);
    process.exit(1);
  }

  const scopeDirs = args.scopeDirs ? args.scopeDirs.split(',').map(d => d.trim()).filter(Boolean) : [];
  const findings = runDebtScan(args.projectRoot, repoMap, { scopeDirs });
  const result = writeFindings(args.output, findings);

  const categoryCounts = {};
  for (const f of findings) {
    categoryCounts[f.category] = (categoryCounts[f.category] || 0) + 1;
  }

  console.log(`debt-scan 完成:`);
  console.log(`  扫描项目: ${args.projectRoot}`);
  console.log(`  发现候选: ${result.total}`);
  console.log(`  写入文件: ${result.written} (跳过已存在: ${result.skipped})`);
  console.log(`  分类分布: ${Object.entries(categoryCounts).map(([k, v]) => `${k}=${v}`).join(', ') || '无'}`);
}
